"""empty message

Revision ID: 02645ef5fc83
Revises: 
Create Date: 2025-06-19 05:08:31.908695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02645ef5fc83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_fullname', sa.String(length=30), nullable=False),
    sa.Column('employee_email', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('employee_email')
    )
    op.create_table('temp_user_informations',
    sa.Column('temp_user_id', sa.Integer(), nullable=False),
    sa.Column('temp_user_email', sa.String(length=60), nullable=False),
    sa.Column('temp_user_fullname', sa.String(length=30), nullable=False),
    sa.Column('temp_user_get_access_date', sa.Date(), nullable=True),
    sa.Column('temp_user_rem_access_date', sa.Date(), nullable=True),
    sa.Column('temp_user_Company', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('temp_user_id'),
    sa.UniqueConstraint('temp_user_email')
    )
    op.create_table('admin_account',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_email', sa.String(length=60), nullable=True),
    sa.Column('admin_username', sa.String(length=30), nullable=False),
    sa.Column('admin_password', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['admin_email'], ['employees.employee_email'], ),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('employee_assets',
    sa.Column('asset_serial', sa.String(length=30), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('first_using_date', sa.Date(), nullable=True),
    sa.Column('last_using_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('asset_serial')
    )
    op.create_table('temp_user_account',
    sa.Column('temp_user_id', sa.Integer(), nullable=False),
    sa.Column('temp_user_password', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['temp_user_id'], ['temp_user_informations.temp_user_id'], ),
    sa.PrimaryKeyConstraint('temp_user_id')
    )
    op.create_table('asset_existence',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('asset_serial', sa.String(length=30), nullable=False),
    sa.Column('existence', sa.String(length=10), nullable=True),
    sa.Column('first_scan_date', sa.Date(), nullable=True),
    sa.Column('last_scan_date', sa.Date(), nullable=True),
    sa.Column('scan_counter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_serial'], ['employee_assets.asset_serial'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'asset_serial')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_existence')
    op.drop_table('temp_user_account')
    op.drop_table('employee_assets')
    op.drop_table('admin_account')
    op.drop_table('temp_user_informations')
    op.drop_table('employees')
    # ### end Alembic commands ###
