"""empty message

Revision ID: 03718396748c
Revises: 1a25c0983811
Create Date: 2025-07-04 05:21:59.676614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03718396748c'
down_revision = '1a25c0983811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'admin_account', ['admin_id'], ['admin_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
