"""adding booleans columns to admin and temp_user

Revision ID: 1a25c0983811
Revises: 3e94b548574d
Create Date: 2025-07-02 06:46:54.413052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a25c0983811'
down_revision = '3e94b548574d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    with op.batch_alter_table('temp_user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_user', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_user_account', schema=None) as batch_op:
        batch_op.drop_column('is_user')

    with op.batch_alter_table('admin_account', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
