"""empty message

Revision ID: 3e94b548574d
Revises: 6c592aa783fa
Create Date: 2025-07-01 07:04:52.618590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e94b548574d'
down_revision = '6c592aa783fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_user_feedback',
    sa.Column('feedback_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_serial', sa.String(length=30), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('asset_temperature', sa.String(length=10), nullable=False),
    sa.Column('asset_noise', sa.String(length=10), nullable=False),
    sa.Column('asset_state', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['asset_serial'], ['asset_existence.asset_serial'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_user_feedback')
    # ### end Alembic commands ###
