"""empty message

Revision ID: 453590eff1e2
Revises: eb4725ec64cb
Create Date: 2025-07-09 10:05:26.821813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '453590eff1e2'
down_revision = 'eb4725ec64cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('employees_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('employees_ibfk_1'), 'admin_account', ['admin_id'], ['admin_id'])

    # ### end Alembic commands ###
