"""empty message

Revision ID: 6c592aa783fa
Revises: e97b2cffa287
Create Date: 2025-06-26 06:05:36.501662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c592aa783fa'
down_revision = 'e97b2cffa287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_user_account', schema=None) as batch_op:
        batch_op.alter_column('temp_user_password',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=False)

    with op.batch_alter_table('temp_user_informations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_user_role', sa.String(length=20), nullable=True))
        batch_op.alter_column('temp_user_get_access_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_user_informations', schema=None) as batch_op:
        batch_op.alter_column('temp_user_get_access_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
        batch_op.drop_column('temp_user_role')

    with op.batch_alter_table('temp_user_account', schema=None) as batch_op:
        batch_op.alter_column('temp_user_password',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
