"""empty message

Revision ID: a348a8f85888
Revises: 02645ef5fc83
Create Date: 2025-06-19 05:33:56.941680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a348a8f85888'
down_revision = '02645ef5fc83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_account', schema=None) as batch_op:
        batch_op.alter_column('admin_password',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_account', schema=None) as batch_op:
        batch_op.alter_column('admin_password',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
