"""empty message

Revision ID: e97b2cffa287
Revises: 184c594d5232
Create Date: 2025-06-19 05:41:36.330763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97b2cffa287'
down_revision = '184c594d5232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_account', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('admin_account_ibfk_1'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_account', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('admin_account_ibfk_1'), 'employees', ['admin_email'], ['employee_email'])

    # ### end Alembic commands ###
