"""empty message

Revision ID: eb4725ec64cb
Revises: 03718396748c
Create Date: 2025-07-08 03:48:28.037043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb4725ec64cb'
down_revision = '03718396748c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_user_feedback', schema=None) as batch_op:
        batch_op.alter_column('asset_temperature',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('asset_noise',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('asset_state',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_user_feedback', schema=None) as batch_op:
        batch_op.alter_column('asset_state',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('asset_noise',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('asset_temperature',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
